apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edcradix
  labels:
    prometheus: playground-v1-5-0-dev
spec:
  endpoints:
  - interval: 2s
    port: http
  jobLabel: edcradix-production
  namespaceSelector:
    matchNames:
    - edcradix-production
  selector:
    matchLabels:
      radixApp: edcradix
      radixComponent: radixquote